# Generated by Django 3.2.15 on 2023-12-25 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bkmonitor', '0150_auto_20231214_1527'),
        ('bkmonitor', '0151_auto_20231219_1701'),
    ]

    operations = [
    ]
